server:
  port: 18081
spring:
  datasource:
    url: jdbc:mysql://119.29.2.229:3306/dubbo-demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: jeff123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-provider
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
dubbo:
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://119.29.2.229:8848
  scan:
    base-packages: cn.itcast.user.service