server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://119.29.2.229:3306/dubbo-demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: jeff123
    driver-class-name: com.mysql.cj.jdbc.Driver